language: node_js
node_js:
  - "8"
env:
    - NODE_ENV='test'
services:
  - mysql
cache:
  directories:
    - "node_modules"
install:
  - npm install
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -u root --password="" test < ./test/db.sql
script:
  - node_modules/mocha/bin/mocha --exit
deploy:
  provider: heroku
  api_key: 87824981-5559-4c57-bf72-9d07c51df180
  app: mighty-reef-55430
  on: master
